extends:
  - stylelint-config-standard-scss
  - stylelint-config-recommended-vue/scss
  - stylelint-config-recess-order
ignoreFiles:
  - .nuxt/**
  - .output/**
  - dist/**
rules:
  selector-id-pattern:
    - '^([a-z][a-z0-9]*)((--?|__?)[a-z0-9]+)*$'
  selector-class-pattern:
    - '^([a-z][a-z0-9]*)((--?|__?)[a-z0-9]+)*$'
