version: 0.2
language: en
words:
  - argb
  - authed
  - auths
  - composables
  - gitea
  - gitee
  - jdenticon
  - kakao
  - livechat
  - luxon
  - mailcow
  - noto
  - nuxt
  - nuxtjs
  - persistedstate
  - pinia
  - planningcenter
  - pocketbase
  - remeda
  - sindresorhus
  - strava
  - unimport
  - vuetify
  - vueuse
  - wght
