version: 0.2
language: en
words:
  - argb
  - luxon
  - materialdesignicons
  - noto
  - nuxt
  - nuxtjs
  - pinia
  - qkeu
  - remeda
  - sindresorhus
  - unimport
  - vuetify
  - vueuse
  - wght
  - yhhjzme
